### ISSUE TITLE
需发布新版本以解决Xcode14.3编译报错的问题

### ISSUE THREAD

**Issue by LinXunFeng** [yulingtianxia/ClassWrittenInSwift#3]
作者好，请问新版本将会在什么时候发布？

关联：解决 Xcode14.3 编译报错的问题 #2

**Comment by yulingtianxia** [comment]
> 作者好，请问新版本将会在什么时候发布？
> 
> 关联：解决 Xcode14.3 编译报错的问题 #2

已发布
